# Generated by Django 4.0 on 2021-12-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('albumspotifyid', models.CharField(db_column='albumSpotifyId', max_length=200, primary_key=True, serialize=False)),
                ('albumname', models.CharField(blank=True, db_column='albumName', max_length=200, null=True)),
                ('artistname', models.CharField(blank=True, db_column='artistName', max_length=100, null=True)),
                ('releasedate', models.DateField(blank=True, db_column='releaseDate', null=True)),
                ('coverart', models.CharField(blank=True, db_column='coverArt', max_length=255, null=True)),
                ('albumstatus', models.CharField(blank=True, db_column='albumStatus', max_length=10, null=True)),
            ],
            options={
                'db_table': 'albums',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('songspotifyid', models.CharField(db_column='songSpotifyId', max_length=255, primary_key=True, serialize=False)),
                ('albumspotifyid', models.CharField(blank=True, db_column='albumSpotifyId', max_length=255, null=True)),
                ('songname', models.CharField(blank=True, db_column='songName', max_length=200, null=True)),
                ('songduration', models.IntegerField(blank=True, db_column='songDuration', null=True)),
                ('songorder', models.IntegerField(blank=True, db_column='songOrder', null=True)),
            ],
            options={
                'db_table': 'songs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Songstreams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songspotifyid', models.CharField(blank=True, db_column='songSpotifyId', max_length=255, null=True)),
                ('daterecorded', models.DateField(blank=True, db_column='dateRecorded', null=True)),
                ('totalstreams', models.BigIntegerField(blank=True, db_column='totalStreams', null=True)),
            ],
            options={
                'db_table': 'songStreams',
                'managed': False,
            },
        ),
    ]
