# Generated by Django 4.0 on 2022-01-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albumdist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsr', models.IntegerField(blank=True, null=True)),
                ('totalstreams', models.BigIntegerField(blank=True, db_column='totalStreams', null=True)),
            ],
            options={
                'db_table': 'albumDist',
                'managed': False,
            },
        ),
    ]
